/**
 * Fallback & Seed Data for Thakre Printing Press
 */

export const SEED_DATA = {
  business: {
    main: {
      name: 'Thakre Printing Press',
      owner: 'Sachin Thakre',
      description: {
        en: 'Professional printing, designing & document services in Goregaon, Gondia.',
        mr: 'गोरेगाव, गोंदिया येथील व्यावसायिक प्रिंटिंग, डिझायनिंग आणि दस्तऐवज सेवा.',
        hi: 'गोरेगांव, गोंदिया में पेशेवर प्रिंटिंग, डिज़ाइनिंग और दस्तावेज़ सेवाएं।',
      },
      phone: '9923113085',
      whatsapp: '9923113085',
      email: 'sachin.thakre@gmail.com',
      address: {
        line1: 'Beside Jamya Timya Zilla Parishad School',
        line2: 'Goregaon Main Road, Gondia–Kohmara Road',
        landmark: 'Beside Jamya Timya Zilla Parishad School',
        city: 'Goregaon',
        district: 'Gondia',
        state: 'Maharashtra',
        country: 'India',
        pin: '441801',
      },
      location: {
        lat: 21.2437,
        lng: 80.2084,
        directions: 'Beside Jamya Timya Zilla Parishad School, Goregaon Main Road, Gondia–Kohmara Road',
      },
      branding: {
        logo: '',
        tagline: 'Quality Printing & Designing at Goregaon',
      },
      socialLinks: {
        facebook: '',
        instagram: '',
        youtube: '',
      },
      familyBusiness: true,
      establishedYear: 2012,
    },
    openingHours: {
      monday: { open: '09:00', close: '20:00', closed: false },
      tuesday: { open: '09:00', close: '20:00', closed: false },
      wednesday: { open: '09:00', close: '20:00', closed: false },
      thursday: { open: '09:00', close: '20:00', closed: false },
      friday: { open: '09:00', close: '20:00', closed: false },
      saturday: { open: '09:00', close: '20:00', closed: false },
      sunday: { open: '', close: '', closed: true },
      holidayNotice: '',
    },
  },
  services: [
    {
      id: 'flex-banner-printing',
      slug: 'flex-banner-printing',
      title: {
        en: 'Flex & Banner Printing',
        mr: 'फ्लेक्स आणि बॅनर प्रिंटिंग',
        hi: 'फ्लेक्स और बैनर प्रिंटिंग',
      },
      shortDescription: {
        en: 'Weather-proof, vibrant large format banners for commercial shops, politics, and family events.',
        mr: 'दुकाने, राजकीय कार्यक्रम आणि घरगुती समारंभांसाठी दर्जेदार वॉटरप्रूफ फ्लेक्स बॅनर.',
        hi: 'दुकानों, कार्यक्रमों और पारिवारिक उत्सवों के लिए उच्च गुणवत्ता वाले वेदर-प्रूफ फ्लेक्स बैनर।',
      },
      description: {
        en: 'We specialize in high-definition large format flex banners, backlit hoardings, star flex, roll-up standees, and vinyl graphics with eyelets and border piping.',
        mr: 'आम्ही एचडी फ्लेक्स, बॅकलिट होर्डिंग्ज, स्टार फ्लेक्स आणि रोल-अप स्टॅन्डीज अचूक फिनिशिंगसह तयार करतो.',
        hi: 'हम एचडी फ्लेक्स, बैकलिट होर्डिंग्स, स्टार फ्लेक्स और स्टैंडी उच्च गुणवत्ता के साथ प्रिंट करते हैं।',
      },
      heroImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
      displayOrder: 1,
      published: true,
      featured: true,
      features: [
        { title: { en: 'Durable Outdoor Material' }, description: { en: 'UV-resistant and waterproof ink for long lifespan' } },
        { title: { en: 'Custom Sizes Available' }, description: { en: 'From small 3x2 ft boards to massive highway hoardings' } },
        { title: { en: 'Fast Turnaround' }, description: { en: 'Urgent printing available within hours' } },
      ],
      enquiryFields: [
        { name: 'width', label: { en: 'Width (Feet)' }, type: 'number', required: true },
        { name: 'height', label: { en: 'Height (Feet)' }, type: 'number', required: true },
        { name: 'material', label: { en: 'Flex Material' }, type: 'select', required: true },
      ],
    },
    {
      id: 'visiting-cards',
      slug: 'visiting-cards',
      title: {
        en: 'Visiting Cards & Business Stationery',
        mr: 'व्हिजिटिंग कार्ड्स आणि स्टेशनरी',
        hi: 'विजिटिंग कार्ड्स और स्टेशनरी',
      },
      shortDescription: {
        en: 'Premium matte, gloss, and textured business cards that leave an unforgettable impression.',
        mr: 'मॅट, ग्लॉस आणि टेक्सचर्ड बिझनेस कार्ड्स.',
        hi: 'मैट, ग्लॉस और प्रीमियम टेक्सचर्ड बिजनेस कार्ड्स।',
      },
      heroImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
      displayOrder: 2,
      published: true,
      featured: true,
      features: [
        { title: { en: '350+ GSM Premium Paper' }, description: { en: 'Sturdy thick cards with crisp edges' } },
        { title: { en: 'Thermal Lamination' }, description: { en: 'Velvet matte or high-shine gloss lamination' } },
      ],
      enquiryFields: [
        { name: 'quantity', label: { en: 'Number of Cards (e.g. 500, 1000)' }, type: 'number', required: true },
        { name: 'finish', label: { en: 'Lamination Finish' }, type: 'select', required: true },
      ],
    },
    {
      id: 'wedding-cards',
      slug: 'wedding-cards',
      title: {
        en: 'Wedding & Invitation Cards',
        mr: 'लग्न आणि आमंत्रण पत्रिका',
        hi: 'शादी और निमंत्रण पत्र',
      },
      shortDescription: {
        en: 'Customized traditional and modern wedding invitations with traditional Marathi fonts & calligraphy.',
        mr: 'मराठी व इंग्रजी सुलेखन आणि आकर्षक डिझाईन्ससह लग्नपत्रिका.',
        hi: 'पारंपरिक और आधुनिक शादी के कार्ड सुंदर सुलेख के साथ।',
      },
      heroImage: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&auto=format&fit=crop&q=80',
      displayOrder: 3,
      published: true,
      featured: true,
      features: [
        { title: { en: 'Exclusive Shubh Vivah Designs' }, description: { en: 'Rich gold foil, embossing, and laser-cut cards' } },
        { title: { en: 'Complete Proof Checking' }, description: { en: 'Accurate Marathi calligraphy proofing before final run' } },
      ],
      enquiryFields: [
        { name: 'quantity', label: { en: 'Number of Invitation Cards' }, type: 'number', required: true },
        { name: 'eventDate', label: { en: 'Wedding / Event Date' }, type: 'text', required: true },
      ],
    },
    {
      id: 'government-forms',
      slug: 'government-forms',
      title: {
        en: 'Government & Legal Forms',
        mr: 'शासकीय आणि न्यायालयीन फॉर्म्स',
        hi: 'सरकारी और कानूनी फॉर्म',
      },
      shortDescription: {
        en: 'Official revenue extracts, affidavits, stamp formats, bonafide formats, and departmental stationery.',
        mr: '७/१२, प्रतिज्ञापत्र, न्यायालयीन अर्ज आणि शासकीय फॉर्म्स.',
        hi: '7/12, शपथ पत्र, कानूनी और सरकारी आवेदन प्रपत्र।',
      },
      heroImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
      displayOrder: 4,
      published: true,
      featured: false,
    },
    {
      id: 'bill-books-registers',
      slug: 'bill-books-registers',
      title: {
        en: 'Bill Books, Challans & Registers',
        mr: 'बिल बुक्स आणि चलन रजिस्टर्स',
        hi: 'बिल बुक्स और चालान रजिस्टर्स',
      },
      shortDescription: {
        en: 'Carbon and carbonless NCR paper invoice books, delivery challans, and receipt books for local shops.',
        mr: 'दुकानांसाठी जीएसटी बिल बुक्स, चलन आणि नंबरिंग रजिस्टर्स.',
        hi: 'दुकानों और व्यवसायों के लिए जीएसटी बिल बुक्स और रसीद पुस्तकें।',
      },
      heroImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
      displayOrder: 5,
      published: true,
      featured: false,
    },
  ],
  forms: [
    {
      id: 'form-7-12',
      name: { en: '7/12 Land Revenue Extract Application', mr: '७/१२ जमीन महसूल उतारा अर्ज' },
      category: 'revenue',
      availability: 'available',
      price: 10,
      displayOrder: 1,
      published: true,
    },
    {
      id: 'form-affidavit',
      name: { en: 'General Stamp Affidavit Format', mr: 'सर्वसाधारण प्रतिज्ञापत्र नमुना' },
      category: 'court',
      availability: 'available',
      price: 20,
      displayOrder: 2,
      published: true,
    },
    {
      id: 'form-income-cert',
      name: { en: 'Income Certificate Application Form', mr: 'उत्पन्न दाखला अर्ज' },
      category: 'government',
      availability: 'available',
      price: 15,
      displayOrder: 3,
      published: true,
    },
    {
      id: 'form-caste-cert',
      name: { en: 'Caste Certificate Application Form', mr: 'जात प्रमाणपत्र अर्ज' },
      category: 'government',
      availability: 'available',
      price: 15,
      displayOrder: 4,
      published: true,
    },
    {
      id: 'form-rto',
      name: { en: 'RTO Driving License Learning Application', mr: 'आरटीओ ड्रायव्हिंग लायसन्स अर्ज' },
      category: 'rto',
      availability: 'available',
      price: 25,
      displayOrder: 5,
      published: true,
    },
  ],
  faqs: [
    {
      id: 'faq-1',
      question: {
        en: 'Where is Thakre Printing Press located?',
        mr: 'ठाकरे प्रिंटिंग प्रेस कुठे आहे?',
        hi: 'ठाकरे प्रिंटिंग प्रेस कहां स्थित है?',
      },
      answer: {
        en: 'We are situated beside Jamya Timya Zilla Parishad School on Goregaon Main Road (Gondia–Kohmara Road), Goregaon, Maharashtra.',
        mr: 'आम्ही जाम्या तिम्या जिल्हा परिषद शाळेजवळ, गोरेगाव मेन रोड (गोंदिया-कोहमारा रोड), गोरेगाव येथे आहोत.',
        hi: 'हम जाम्या तिम्या ज़िला परिषद स्कूल के पास, गोरेगांव मेन रोड (गोंदिया-कोहमारा रोड), गोरेगांव में स्थित हैं।',
      },
      category: 'General',
      displayOrder: 1,
      published: true,
    },
    {
      id: 'faq-2',
      question: {
        en: 'Can I send my design directly on WhatsApp for printing?',
        mr: 'मी प्रिंटिंगसाठी डिझाईन थेट व्हॉट्सॲपवर पाठवू शकतो का?',
        hi: 'क्या मैं प्रिंटिंग के लिए डिज़ाइन सीधे व्हाट्सएप पर भेज सकता हूं?',
      },
      answer: {
        en: 'Yes! You can message us on WhatsApp at 9923113085 with your PDF or high-resolution images, and we will inspect the resolution and print it immediately.',
        mr: 'होय! तुम्ही ९९२३११३०८५ या क्रमांकावर व्हॉट्सॲपवर फाईल पाठवू शकता, आम्ही त्वरित काम सुरू करतो.',
        hi: 'हाँ! आप 9923113085 पर व्हाट्सएप कर सकते हैं, हम तुरंत प्रिंटिंग शुरू कर देंगे।',
      },
      category: 'Files & Orders',
      displayOrder: 2,
      published: true,
    },
    {
      id: 'faq-3',
      question: {
        en: 'Do you offer same-day banner printing for urgent events?',
        mr: 'तातडीच्या कार्यक्रमांसाठी त्याच दिवशी बॅनर प्रिंटिंग उपलब्ध आहे का?',
        hi: 'क्या आवश्यक कार्यक्रमों के लिए उसी दिन बैनर प्रिंटिंग उपलब्ध है?',
      },
      answer: {
        en: 'Yes, urgent flex banner printing is supported. Depending on banner size and workload, most urgent jobs can be ready within 2 to 4 hours.',
        mr: 'होय, तातडीच्या कामांसाठी २ ते ४ तासांत बॅनर प्रिंट करून दिले जातात.',
        hi: 'हाँ, तात्कालिक बैनर प्रिंटिंग 2 से 4 घंटे के भीतर उपलब्ध कराई जाती है।',
      },
      category: 'Timeline',
      displayOrder: 3,
      published: true,
    },
  ],
};
